//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Agregados
{
    using System;
    using System.Collections.Generic;
    
    public partial class BitacoraVehiculo
    {
        public int IdBitacora { get; set; }
        public System.DateTime FechaIngreso { get; set; }
        public string HoraIngreso { get; set; }
        public Nullable<System.DateTime> FechaSalida { get; set; }
        public string HoraSalida { get; set; }
        public string Motivo { get; set; }
        public string Solucion { get; set; }
        public string Mecanico { get; set; }
        public Nullable<decimal> CostoReparacion { get; set; }
        public int IdVehiculo { get; set; }
        public int IdEstado { get; set; }
        public int IdUsuario { get; set; }
    
        public virtual Estados Estados { get; set; }
        public virtual Usuarios Usuarios { get; set; }
        public virtual Vehiculos Vehiculos { get; set; }
    }
}
