//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Agregados
{
    using System;
    using System.Collections.Generic;
    
    public partial class CierreApertCajas
    {
        public int IdCierreApert { get; set; }
        public System.DateTime Fecha { get; set; }
        public System.TimeSpan Hora { get; set; }
        public string Detalles { get; set; }
        public decimal MontoEfectivo { get; set; }
        public decimal MontoTransf { get; set; }
        public decimal MontoSinpe { get; set; }
        public decimal MontoCheque { get; set; }
        public decimal MontoCredito { get; set; }
        public int IdUsuario { get; set; }
    
        public virtual Usuarios Usuarios { get; set; }
    }
}
