//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Agregados
{
    using System;
    using System.Collections.Generic;
    
    public partial class Denominaciones
    {
        public int IdDenominacion { get; set; }
        public int MonedasCinco { get; set; }
        public int MonedasDiez { get; set; }
        public int MonedasVeinteCinco { get; set; }
        public int MonedasCincuenta { get; set; }
        public int MonedasCien { get; set; }
        public int MonedasQuinientos { get; set; }
        public int BilleteMil { get; set; }
        public int BilleteDosMil { get; set; }
        public int BilleteCincoMil { get; set; }
        public int BilleteDiezMil { get; set; }
        public int BilleteVeinteMil { get; set; }
        public int IdCierreApert { get; set; }
        public byte AperturaCierre { get; set; }
    
        public virtual CierreApertCajas CierreApertCajas { get; set; }
    }
}
