//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Agregados
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleFact
    {
        public int IdDetalle { get; set; }
        public decimal Cantidad { get; set; }
        public decimal Precio { get; set; }
        public int IdFactura { get; set; }
        public int IdMaterial { get; set; }
    
        public virtual Factura Factura { get; set; }
        public virtual Material Material { get; set; }
    }
}
