//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Agregados
{
    using System;
    using System.Collections.Generic;
    
    public partial class Facturas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Facturas()
        {
            this.DetalleFacts = new HashSet<DetalleFacts>();
        }
    
        public int IdFactura { get; set; }
        public int Consecutivo { get; set; }
        public decimal CostoTransporte { get; set; }
        public decimal Subtotal { get; set; }
        public decimal IVA { get; set; }
        public decimal CostoTotal { get; set; }
        public System.DateTime FechaFactura { get; set; }
        public Nullable<decimal> MontoPendiente { get; set; }
        public Nullable<System.DateTime> FechaLimiteP { get; set; }
        public string ReferenciaPago { get; set; }
        public Nullable<decimal> BackHoe { get; set; }
        public Nullable<decimal> Tierra { get; set; }
        public Nullable<decimal> CantTierra { get; set; }
        public string DetalleNoCobroIVA { get; set; }
        public string FactProveedor { get; set; }
        public byte PrecioEspecial { get; set; }
        public decimal Descuento { get; set; }
        public int IdUsuario { get; set; }
        public int IdTipo { get; set; }
        public int IdEstado { get; set; }
        public Nullable<int> IdCliente { get; set; }
        public Nullable<int> IdProveedor { get; set; }
        public int IdTipoPago { get; set; }
        public int IdCierreApert { get; set; }
        public Nullable<int> NotaDebitoIDFact { get; set; }
    
        public virtual CierreApertCajas CierreApertCajas { get; set; }
        public virtual Clientes Clientes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleFacts> DetalleFacts { get; set; }
        public virtual Estados Estados { get; set; }
        public virtual MetodosPagos MetodosPagos { get; set; }
        public virtual Proveedores Proveedores { get; set; }
        public virtual TiposFacturas TiposFacturas { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
