//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Agregados
{
    using System;
    using System.Collections.Generic;
    
    public partial class Factura
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Factura()
        {
            this.DetalleFacts = new HashSet<DetalleFact>();
        }
    
        public int IdFactura { get; set; }
        public decimal CostoTransporte { get; set; }
        public decimal IVA { get; set; }
        public decimal CostoTotal { get; set; }
        public System.DateTime FechaFactura { get; set; }
        public Nullable<System.DateTime> FechaLimiteP { get; set; }
        public int IdUsuario { get; set; }
        public int IdTipo { get; set; }
        public int IdEstado { get; set; }
        public Nullable<int> IdCliente { get; set; }
        public Nullable<int> IdProveedor { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleFact> DetalleFacts { get; set; }
        public virtual Estado Estado { get; set; }
        public virtual Provedor Provedor { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual TipoFactura TipoFactura { get; set; }
    }
}
